title: My Personal Site
description: Welcome to my GitHub Pages site
url: "https://joslinmariathomas.github.io"
baseurl: "" # leave empty if using username.github.io
theme: jekyll-theme-minima
# Optional
show_downloads: false
